version: '3.8'

services:

  proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8888:80
    depends_on:
      - backend
      
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./MesSenderBack
    restart: on-failure:3
    depends_on:
      - pg_db
    environment:
      - DB_HOST=pg_db
      - DB_PORT=5432
      - DB_PASS=postgres
      - DB_USER=postgres

  pg_db:
    image: postgres:alpine3.19
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres

  